CREATE DATABASE customer_shopping;

SHOW DATABASES;

USE customer_shopping;

CREATE TABLE customer_behavior (
    customer_id INT,
    age INT,
    gender VARCHAR(20),
    item_purchased VARCHAR(100),
    category VARCHAR(50),
    purchase_amount DECIMAL(10,2),
    location VARCHAR(50),
    size VARCHAR(10),
    color VARCHAR(30),
    season VARCHAR(20),
    review_rating DECIMAL(3,2),
    subscription_status VARCHAR(20),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(10),
    previous_purchases INT,
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(50),
    age_group VARCHAR(20),
    purchase_frequency_days INT
);

-- Q1. what is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue 
from customer_behavior
group by gender;

-- Q2. which customers used discount but still spend more than the average purchase amount?
select customer_id, purchase_amount
from customer_behavior
where discount_applied = 'yes' and purchase_amount >= (select AVG (purchase_amount) from customer_behavior);

-- Q3. which are the top 5 products with the highest average review rating?
select item_purchased, round(avg (review_rating ),2) as ' review product rating'
from customer_behavior
group by item_purchased
order by avg (review_rating) desc
limit 5;
-- Q4. compare the average purchase amounts between standards and express shipping.
select shipping_type, round(avg(purchase_amount),2) 
from customer_behavior
where shipping_type in ('standard','express')
group by shipping_type;

-- Q5. do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue 
from customer_behavior
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. which 5 products have the highest percentage of purchases with discounts applied?    
select item_purchased,
round(sum(case when discount_applied = 'yes' then 1 else 0 end )/count(*) * 100,2) as discount_rate
from customer_behavior
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. segment customer into new, returning and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
    end as customer_segment
from customer_behavior
)

select customer_segment, count(*) as "number of segment"
from customer_type
group by customer_segment;

-- Q8. what are top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_behavior
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_behavior
where previous_purchases > 5
group by subscription_status;

-- Q10. whate is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc;